sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
env:
  - CXX=g++-4.8
addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release
