sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release
