sudo: false
language: node_js
node_js: stable
branches:
  only:
    - master
notifications:
  email: false
addons:
  firefox: latest
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g codeclimate-test-reporter
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - npm run semantic-release
